### ISSUE TITLE
Can't open CE App from Sidebar

### ISSUE THREAD

**Issue by ctbritt** [DFreds/dfreds-convenient-effects#216]
**Describe the bug**
Can't open the app from the left sidebar in v4.0
**To Reproduce**
1. click on CE icon in left sidebar
2. nothing happens

**Expected behavior**
App opens

**Screenshots**
F12 console error
<img width="573" alt="CleanShot 2023-02-24 at 16 09 57@2x" src="https://user-images.githubusercontent.com/4516034/221295784-d340ed3c-f0be-4e68-9889-dd629601ef13.png">
**Additional context**

**Comment by guldelox** [comment]
I'm also experiencing this, with all other modules disabled it's still throwing this error and failing to open from the sidebar.

**Comment by DFreds** [comment]
Oh, weird. I think I know why, thanks for bringing it up

**Comment by DFreds** [comment]
I think this might be occurring due to older custom effects missing new flags that are assumed to be set. Can you check if it persists in 4.0.1?

**Comment by DFreds** [comment]
Fixed in v4.0.1 as I was able to reproduce it and it is no longer occurring. Let me know if you find otherwise

**Comment by guldelox** [comment]
Issue is still occurring in 4.0.1 for me: 
![image](https://user-images.githubusercontent.com/67302749/221320878-04b7c7bb-35b9-47b8-bc52-82dfbf52ac69.png)

**Comment by DFreds** [comment]
Ah, yeah. Actually a separate issue. Logged here: #218
